version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    command: mysqld
    environment:
      MYSQL_USER: mysql
      MYSQL_ROOT_PASSWORD: sha256_password
      MYSQL_DATABASE: mysql_nest
    ports:
      - "3306:3306"
    networks:
      - freecodecamp
networks:
  freecodecamp:
